sudo: false

language: node_js

node_js:
    - '12'

branches:
    only:
        - master

cache:
    directories:
        - node_modules

install:
    - npm install

script:
  - npm run build
  - npm test
